### ISSUE TITLE
Input -> add props to valid list of props

### ISSUE THREAD

**Issue by Mhsmit** [deg/sodium#5]
Can you also add **:on-blur**, **:on-focus** to the list of valid input props? They work with soda-ash so I guess they also should be here and for field validation they are rather essential. 

**:on-keypress** would also be nice, but I think Sodium has a typo. When I add **:on-keypress** it produces an error ... although ... **:on-keyPress** works

I am rather new at this github stuff and I am little bit hesitant of doing a pull request and update it myself.... maybe I screw things up for you :D

**Comment by deg** [comment]
Sure. I will try to do this later this week or next, when I have some time.

Or, I'm happy to accept a pull request if you want to try. I don't think you can screw up anything for me in a pull request. The worst possibility is that you get something wrong in the PR and I ask you to fix it.

**Comment by deg** [comment]
Fixed in Sodium v0.12.0.  I've added :on-blur, :on-focus, :on-keyPress, :on-keyUp, and :on-keyDown.

It looks like Semantic-UI does not support the all-lowercase spellings of :on-key*.
